import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
    alignItems: 'center',
  },
  city: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  temp: {
    fontSize: 48,
    fontWeight: '800',
    color: '#1E90FF',
    marginTop: 8,
  },
  desc: {
    fontSize: 16,
    color: '#6B7280',
    marginTop: 6,
    textTransform: 'capitalize',
  },
  metaRow: {
    flexDirection: 'row',
    marginTop: 12,
    width: '100%',
    justifyContent: 'space-between',
  },
  metaText: {
    fontSize: 14,
    color: '#374151',
  },
  retryButton: {
    marginTop: 12,
    backgroundColor: '#1E90FF',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  retryText: {
    color: '#fff',
    fontWeight: '600',
  },
  error: {
    color: '#DC2626',
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  hint: {
    color: '#6B7280',
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  topContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 8,
  },
  searchButton: {
    width: 36,
    height: 36,
    backgroundColor: '#1E90FF',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  searchIcon: {
    width: 18,
    height: 18,
    tintColor: '#fff',
  },
  moreButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    zIndex: 2,
  },
  moreIcon: {
    width: 18,
    height: 18,
    tintColor: '#6B7280',
  },
  navButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E90FF',
  },
  navIcon: {
    width: 18,
    height: 18,
    tintColor: '#fff',
  },
  loadingOverlay: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
});

export default styles;
